name: Build and Test

on:
  push:
    branches:
      - branchMake

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install build tools
      run: sudo apt update && sudo apt install -y build-essential

    - name: Build project
      run: make

    - name: Build tarball
      run: |
        ./configure
        make dist

    - name: Build Debian package
      run: |
        make dist
        dpkg-buildpackage -us -uc
